### ISSUE TITLE
3.11.2c破解完整性校验会导致游戏崩溃

### ISSUE THREAD

**Issue by shacha086** [ArcaeaMemory/ArcaeaModder#1]
复现方式：
下载3.11.2c
将三个破解都打开
替换so文件
修改包名
打开游戏
（并没有修改游戏slst内容

**Comment by ArcaeaMemory** [comment]
初3.5.3c以外的版本均为不可用(测试)状态
此项目大概会在今年的愚人节版本后继续

**Comment by shacha086** [comment]
> 初3.5.3c以外的版本均为不可用(测试)状态 此项目大概会在今年的愚人节版本后继续

谢谢，辛苦了
