### ISSUE TITLE
crashes when trying to open the game

### ISSUE THREAD

**Issue by Refute97** [ArcaeaMemory/ArcaeaModder#3]
why doesn't the armeabi-v7a option work?, when editing the songlist file and adding the April fools chart file it crashes when opening the game

**Comment by huoyan1231** [comment]
use 3.5.3
3.12.6 is test. it don't work

**Comment by Refute97** [comment]
but in that version it doesn't support April fools chart this year

**Comment by huoyan1231** [comment]
> but in that version it doesn't support April fools chart this year

You can modify 3.12.6 armeabi-v7a yourself
ArcaeaModder is not required
