### ISSUE TITLE
....

### ISSUE THREAD

**Issue by Ayanokouj1-kun** [ArcaeaMemory/ArcaeaModder#4]

**Comment by huoyan1231** [comment]
Find them yourself
自己找

**Comment by Ayanokouj1-kun** [comment]
Sorry but I'm still a student and still learning things like that can you please help me?

**Comment by huoyan1231** [comment]
> Sorry but I'm still a student and still learning things like that can you please help me?

No.
it difficult sinse 3.10
不是中国人吗？

**Comment by Ayanokouj1-kun** [comment]
It's Chinese vee

**Comment by huoyan1231** [comment]
> 

说中文谢谢

**Comment by Ayanokouj1-kun** [comment]
No I'm not Chinese I'm talking about the version of my Arcaea which is Chinese ver

**Comment by huoyan1231** [comment]
> No I'm not Chinese I'm talking about the version of my Arcaea which is Chinese ver

Chinese ver. is same as Google ver.
but chinese not required Google play, and it can pay with Alipay
3.12.6c =  3.12.6

**Comment by Ayanokouj1-kun** [comment]
You kinda out of place here aren't we talking about offsets here but these offsets are still lack of something so I just want to ask if there's a easier option to find out those.

**Comment by huoyan1231** [comment]
Use IDA

**Comment by innocentvoice** [comment]
> You kinda out of place here aren't we talking about offsets here but these offsets are still lack of something so I just want to ask if there's a easier option to find out those.

Find it yourself skid
If you find this useless then don't use it.

别问别人了，你这个笨蛋

**Comment by huoyan1231** [comment]
> > You kinda out of place here aren't we talking about offsets here but these offsets are still lack of something so I just want to ask if there's a easier option to find out those.
> 
> Find it yourself skid If you find this useless then don't use it.
> 
> 别问别人了，你这个笨蛋

支持正义爆杀
