### ISSUE TITLE
 it doesnt work

### ISSUE THREAD

**Issue by Loidk** [ArcaeaMemory/ArcaeaModder#5]
ㅤ

**Comment by Loidk** [comment]
/data/user/0/com.gmail.heagoo.apkeditor.pro/files/decoded/AndroidManifest.xml:40: error: No resource identifier found for attribute 'allowNativeHeapPointerTagging' in package 'android'

**Comment by AMONGUSSUSSYSUSSUS** [comment]
The reason why you can't edit it because you're retarded
![918103510506160158-1](https://user-images.githubusercontent.com/103934820/165213490-46015042-b2c4-4d29-94d1-248c660daa3c.png)

**Comment by innocentvoice** [comment]
> .

Close this issue lol this is not related to ArcaeaModder and such 
![image](https://user-images.githubusercontent.com/81401361/165217731-2cb53d98-877e-4dae-862b-acb69c183722.png)
and editing your comment is useless
